# Generated by Django 3.2.6 on 2023-08-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudRegistroMiembro',
        ),
    ]
