# Generated by Django 3.2.6 on 2022-07-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consejodia', '0003_novedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='user',
        ),
        migrations.AddField(
            model_name='novedad',
            name='celular',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='nombre',
            field=models.TextField(null=True),
        ),
    ]
