# Generated by Django 3.2.6 on 2022-07-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consejodia', '0005_detallereaccionconsejo_reaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejodia',
            name='path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='novedad',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
