# Generated by Django 3.2.6 on 2022-08-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consejodia', '0006_auto_20220726_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejodia',
            name='fijado',
            field=models.BooleanField(default=0),
        ),
    ]
