# Generated by Django 3.2.6 on 2022-06-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentarioruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallearchivoruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleetiquetaruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rastreoruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
