# Generated by Django 3.2.6 on 2022-07-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_auto_20220619_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiqueta',
            new_name='EtiquetaRuta',
        ),
    ]
