# Generated by Django 3.2.6 on 2022-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0004_auto_20220718_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
    ]
