# Generated by Django 3.2.6 on 2022-08-07 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0008_colaboracion_detallecolaboracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='estimado_tiempo',
        ),
        migrations.AddField(
            model_name='ruta',
            name='cancelada',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='motivo_cancelacion',
            field=models.TextField(default=None, null=True),
        ),
    ]
