# Generated by Django 3.2.6 on 2022-08-11 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ruta', '0009_auto_20220807_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='cupos_disponibles',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DetalleColaboracionInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('colaboracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.colaboracion')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.ruta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
