# Generated by Django 3.2.6 on 2022-08-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0011_ruta_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionruta',
            name='finalizado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='safe',
            field=models.BooleanField(null=True),
        ),
    ]
