# Generated by Django 3.2.6 on 2022-08-16 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0012_auto_20220814_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('nombre', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePuntoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('lugar', models.TextField()),
                ('grupo_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.grupoencuentro')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.ruta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
