# Generated by Django 3.2.6 on 2022-08-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0013_detallepuntoencuentro_grupoencuentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionruta',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='estrellas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='horas',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='kilocalorias',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='kilometros',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inscripcionruta',
            name='velocidad',
            field=models.FloatField(null=True),
        ),
    ]
