# Generated by Django 3.2.6 on 2022-08-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0014_auto_20220820_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastreoruta',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='rastreoruta',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='rastreoruta',
            name='user',
        ),
        migrations.DeleteModel(
            name='ComentarioRuta',
        ),
        migrations.DeleteModel(
            name='RastreoRuta',
        ),
    ]
