# Generated by Django 3.2.6 on 2022-09-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0015_auto_20220820_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='cupos_totales',
            field=models.IntegerField(null=True),
        ),
    ]
