# Generated by Django 3.2.6 on 2024-12-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0007_auto_20241206_1702'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_detalles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaCiclistaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('VISTA_MAPA', 'Vista Mapa Ecuaciclismo')], default='VISTA_MAPA', max_length=100)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
