# Generated by Django 3.2.6 on 2022-07-18 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consejodia', '0005_detallereaccionconsejo_reaccion'),
        ('publicacion', '0003_auto_20220704_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReaccionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacion.publicacion')),
                ('reaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consejodia.reaccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
