# Generated by Django 3.2.6 on 2022-07-23 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_detallereaccionpublicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiquetapublicacion',
            old_name='descripcion',
            new_name='value',
        ),
    ]
