# Generated by Django 3.2.6 on 2022-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_rename_descripcion_etiquetapublicacion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopublicacion',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
