# Generated by Django 3.2.6 on 2023-07-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0002_auto_20230725_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha_fin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='motivo_cancelacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
