# Generated by Django 3.2.6 on 2023-07-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerta', '0003_auto_20230726_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioalerta',
            name='padre',
        ),
    ]
