# Generated by Django 3.2.6 on 2023-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenbicicleta',
            name='imagen_url',
            field=models.CharField(max_length=200),
        ),
    ]
