# Generated by Django 3.2.6 on 2023-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleta', '0002_alter_imagenbicicleta_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenbicicleta',
            name='path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagenbicicleta',
            name='imagen_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
