# Generated by Django 3.2.6 on 2023-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleta', '0003_auto_20231214_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
