# Generated by Django 3.2.6 on 2024-01-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicleta', '0005_auto_20240112_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='modadlidad',
            new_name='modalidad',
        ),
    ]
