# Generated by Django 3.2.6 on 2022-06-21 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_detalleusuario_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('foto_bicicleta', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='celular',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='foto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='genero',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DetalleBicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.bicicleta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
