# Generated by Django 3.2.6 on 2022-07-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20220621_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleusuario',
            name='token_notificacion',
            field=models.TextField(null=True),
        ),
    ]
