# Generated by Django 3.2.6 on 2022-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_detalleusuario_token_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleusuario',
            name='peso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalleusuario',
            name='nivel',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='DetalleBicicleta',
        ),
    ]
