# Generated by Django 3.2.6 on 2022-08-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0015_auto_20220820_1844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0006_detalleusuario_bicicleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='modelo',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='codigo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='foto_bicicleta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DetalleEtiquetaRutaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ruta.etiquetaruta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
