# Generated by Django 3.2.6 on 2022-08-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_detalleusuario_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleusuario',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
