# Generated by Django 3.2.6 on 2023-07-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0009_auto_20220821_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('isUser', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='isPropietary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleusuario',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='GrupoContactoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('contacto_seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.contactoseguro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
