# Generated by Django 3.2.6 on 2023-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20230724_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleusuario',
            name='tipo',
            field=models.CharField(default='No verificado', max_length=20, null=True),
        ),
    ]
