# Generated by Django 3.2.6 on 2023-08-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_detalleusuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleusuario',
            name='silenciar_notificaciones',
            field=models.BooleanField(default=False),
        ),
    ]
