# Generated by Django 3.2.6 on 2023-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_detalleusuario_silenciar_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleusuario',
            name='tipo',
            field=models.CharField(default='Miembro', max_length=20, null=True),
        ),
    ]
