# Generated by Django 3.2.6 on 2023-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_alter_local_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='celular',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
