# Generated by Django 3.2.6 on 2023-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0003_auto_20230806_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion_atencion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion_limpieza',
            field=models.IntegerField(null=True),
        ),
    ]
