# Generated by Django 3.2.6 on 2023-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0004_auto_20230814_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='isParqueadero',
            field=models.BooleanField(null=True),
        ),
    ]
