# Generated by Django 3.2.6 on 2024-11-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0016_ruta_cupos_totales'),
        ('lugar', '0005_local_isparqueadero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ruta.ubicacion'),
        ),
    ]
