# Generated by Django 3.2.6 on 2024-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_detalles', '0001_initial'),
        ('lugar', '0006_alter_lugar_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='productos',
            field=models.ManyToManyField(related_name='locales', to='local_detalles.Producto'),
        ),
        migrations.AddField(
            model_name='local',
            name='servicios_adicionales',
            field=models.ManyToManyField(related_name='locales', to='local_detalles.ServicioAdicional'),
        ),
    ]
