# Generated by Django 3.2.6 on 2024-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_detalles', '0001_initial'),
        ('lugar', '0006_alter_lugar_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='servicio_detalles',
            field=models.ManyToManyField(related_name='locales', to='local_detalles.ServicioDetalle'),
        ),
        migrations.AddField(
            model_name='local',
            name='tipo_productos',
            field=models.ManyToManyField(related_name='locales', to='local_detalles.TipoProducto'),
        ),
    ]
