# Generated by Django 3.2.6 on 2023-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='uuidLog',
            field=models.CharField(max_length=100),
        ),
    ]
