name: Deployment to staging

on:
  push:
    branches:
      - staging

jobs:
  checkout-repository:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v2
        with:
          name: ecuaciclismo
          path: /

  deploy-backend:
    needs: [checkout-repository]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ecuaciclismo
          path: /
      - name: Open backend folder
        run: cd backend
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install

  deploy-frontend:
    needs: [checkout-repository]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ecuaciclismo
          path: /
      - name: Open frontend folder
        run: cd frontend
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install
