name: Deployment to staging

on:
  push:
    branches:
      - staging

jobs:
  checkout-repository:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v2
        with:
          name: ecuaciclismo
          path: /home/runner/work/ecua-ciclismo/ecua-ciclismo

  deploy-backend:
    needs: [checkout-repository]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ecuaciclismo
          path: /home/runner/work/ecua-ciclismo/ecua-ciclismo
      - name: Open backend folder
        run: cd backend
      # - uses: jensvog/pythonanywhere-webapp-reload-action@v1
      #   with:
      #     host: ecuacilismoApp.mysql.pythonanywhere-services.com
      #     username: ecuacilismoApp
      #     api-token: 1ea811d29d67d939659a3c9c99ec49cd1e4c5658
      #     domain-name: ecuacilismoApp.pythonanywhere.com.

  # deploy-frontend:
  #   needs: [checkout-repository]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: ecuaciclismo
  #         path: /home/runner/work/ecua-ciclismo/ecua-ciclismo
  #     - name: Install Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #     - name: Install yarn
  #       run: npm install -g yarn
  #     - name: Install global eslint
  #       run: npm i eslint -g
  #     - name: Install Dependencies
  #       run: cd frontend ; yarn install
  #     - name: Ejecutar reglas de eslint
  #       run: cd frontend ; yarn eslint
