name: Deployment to production

on:
  push:
    branches:
      - main

jobs:
  checkout-repository:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: eu.pythonanyhwere.com
          username: ecuaciclismoApp
          api-token: 508bea321c8ab2f92fca799c33bf58335c6f9038
          domain-name: ecuacilismoApp.pythonanywhere.com
