name: Deployment to staging

on:
  push:
    branches:
      - staging

jobs:
  checkout-repository:
    runs-on: ubuntu-18.04
    # steps:
    #   - name: Checkout Repository
    #     uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0
